### ISSUE TITLE
Test names could provide more information

### ISSUE THREAD

**Issue by dario-campagna** [FedericoPolli/Cribbage-assignment#1]
Whenever a test breaks, the test name is the first thing you see, so it should communicate as much as possible.

https://github.com/FedericoPolli/Cribbage-assignment/blob/c5752ff6485ce634069ab50d5825a50e448db867/src/test/java/dssc/assignment/cribbage/ScoreTest.java#L22

**Comment by FedericoPolli** [comment]
Ok, renamed the tests to precisely convey the expectedd score.
