### ISSUE TITLE
Message chains and feature envy

### ISSUE THREAD

**Issue by dario-campagna** [FedericoPolli/Cribbage-assignment#10]
This is one of the example of message chain smell in this class. This method is also one of the example of feature envy in this class. I'd try to move more methods in CribbageHand to work on these smells.

https://github.com/FedericoPolli/Cribbage-assignment/blob/c5752ff6485ce634069ab50d5825a50e448db867/src/main/java/dssc/assignment/cribbage/CribbageScoreCalculator.java#L39

**Comment by FedericoPolli** [comment]
Originally almost all the methods were in the CribbageHand class, as are now after refactoring. I had moved them as I felt that the CribbageHand class was too large, whereas the CribbageScoreCalculator, having only one method, seemed not important enough to actually exist as a class. But as you pointed out I created many smells by doing this, so I reverted back.

**Comment by FedericoPolli** [comment]
Now my question are: what should I do with the CribbageScoreCalculator class? Leave it as it is, delete it and calculate the score in CribbageHand, or move some methods from CribbageHand to it? The only methods which would not cause feature envy are NormalRuns() and RunsWithAceHigh(), but moving only those two doesn't seem logically correct. And is CribbageHand too large? 
In any case I will try to simplify the methods with streams to reduce the complexity of the class.

**Comment by dario-campagna** [comment]
I’d try to simplify the method in CribbageHand as you suggest before reasoning about its size. The getCribbageScore method can be removed in my opinion.

The getCribbageScore method in CribbageScoreCalculator could be improved by extracting some methods.

**Comment by FedericoPolli** [comment]
I simplified many methods in CribbageHand via streams and by extracting methods, although I was unable to avoid a double for loop in NormalRuns. How else should I improve the class?
I also extracted some methods in getCribbageScore in CribbageScoreCalculator to improve readability.

**Comment by dario-campagna** [comment]
Both classes look fine to me. One further improvement could be to move in Rank the check on the run. You're basically checking that you have a list of consecutive ranks.

**Comment by FedericoPolli** [comment]
Ok, moved the method. Thank you very much for your help, if you do not have any other suggestions I'll close the issue.
