### ISSUE TITLE
Methods readability

### ISSUE THREAD

**Issue by dario-campagna** [FedericoPolli/Cribbage-assignment#11]
The readability of the two methods in this class can be improved. For the example, in GenerateSubsetSums stream can be used to reduce the number of lines.

https://github.com/FedericoPolli/Cribbage-assignment/blob/c5752ff6485ce634069ab50d5825a50e448db867/src/main/java/dssc/assignment/cribbage/Utilities.java#L7

**Comment by FedericoPolli** [comment]
I refactored GenerateSubsetSums to use streams. How else can I improve the readability?

**Comment by dario-campagna** [comment]
In GenerateSubsetSums streams can be used to replace the remaining for-loop too. Try and see if the readability of the method improves or not.

For the other method I’d try to improve it with extract method.

**Comment by FedericoPolli** [comment]
I have replaced the remaining for loop with streams in the GenerateSubsetSums method(), although I am not sure whether readability has actually improved. I left the previous code commented so it's immediately comparable. 
I have also extracted a populatePowerset method() in GeneratePowerset().

**Comment by dario-campagna** [comment]
The readability is improved in my opinion. It can be further improved by extracting `subset -> subset.stream().mapToInt(Integer::intValue).sum()` into a method.

**Comment by FedericoPolli** [comment]
True, I had not thought about that. It is definitely clearer now, thanks.
 If you do not have any other suggestions I can close this issue.
