### ISSUE TITLE
Card equals in tests

### ISSUE THREAD

**Issue by dario-campagna** [FedericoPolli/Cribbage-assignment#2]
You could use the Card equals method for the assertion in this and other tests.

https://github.com/FedericoPolli/Cribbage-assignment/blob/c5752ff6485ce634069ab50d5825a50e448db867/src/test/java/dssc/assignment/cribbage/ParseCribbageHandTest.java#L12

**Comment by FedericoPolli** [comment]
True, I only added the equals method towards the end of the project so I forgot.
