### ISSUE TITLE
Test can fail for more than one reason

### ISSUE THREAD

**Issue by dario-campagna** [FedericoPolli/Cribbage-assignment#3]
This test (and also the following one) can fail for two reasons. Issues with the parse method and issues with the isAce method. It’s better to test different behaviors in different tests.

https://github.com/FedericoPolli/Cribbage-assignment/blob/c5752ff6485ce634069ab50d5825a50e448db867/src/test/java/dssc/assignment/cribbage/ParseCribbageHandTest.java#L22

**Comment by FedericoPolli** [comment]
Ok, modified tests to test only for a single behaviour.
