### ISSUE TITLE
Single Responsibility Principle violation

### ISSUE THREAD

**Issue by dario-campagna** [FedericoPolli/Cribbage-assignment#4]
The CardParser class is also responsible for parsing ranks and suite. I’d try to move parseRank and parseSuite to the respective enum (or to new classes).

https://github.com/FedericoPolli/Cribbage-assignment/blob/c5752ff6485ce634069ab50d5825a50e448db867/src/main/java/dssc/assignment/cribbage/CardParser.java#L5

**Comment by FedericoPolli** [comment]
True, I hadn't thought about that. Moved the methods to the respective enums.
