### ISSUE TITLE
Behaviors with no tests

### ISSUE THREAD

**Issue by dario-campagna** [FedericoPolli/Cribbage-assignment#8]
It seems that there's no test for the exceptions thrown by the CribbageHand constructor.

https://github.com/FedericoPolli/Cribbage-assignment/blob/c5752ff6485ce634069ab50d5825a50e448db867/src/main/java/dssc/assignment/cribbage/CribbageHand.java#L21

**Comment by FedericoPolli** [comment]
Added testing for exceptions for both CardParser and CribbageHand constructor.
